# -*- coding: utf-8 -*-
"""diagnose_new.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vW0mbXJ6Q5RybZ5gFSH3_FfGzoNjwiZy
"""
import tensorflow as tf
from tensorflow.keras.preprocessing import *
from PIL import Image


def diagnose_with_model(img):
    img = Image.open(img)

    # load the model
    model_path = 'cnn/data/Model'
    model = tf.keras.models.load_model(model_path)
    
    # check the image size
    if (img.size[0]!=50 or img.size[1]!=50):
        return -1
    
    # preprocessing
    img = image.img_to_array(img)
    img /= 255.0
    
    # predict it with the cnn model
    y_prob = model.predict(img.reshape(-1,50,50,3))

    # return the classified result 0/1
    if y_prob > 0.5:
        return 1
    else:
        return 0


if __name__ == '__main__':
    ...
